[2024-06-19T15:35:04.883+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: testing_dag.task_2 manual__2024-06-19T15:34:42.116372+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
