[2024-06-19T14:32:36.727+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T14:32:36.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_dag.test_task manual__2024-06-19T14:32:34.573297+00:00 [queued]>
[2024-06-19T14:32:36.761+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_dag.test_task manual__2024-06-19T14:32:34.573297+00:00 [queued]>
[2024-06-19T14:32:36.762+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T14:32:36.777+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_task> on 2024-06-19 14:32:34.573297+00:00
[2024-06-19T14:32:36.785+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=512) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T14:32:36.786+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'test_task', 'manual__2024-06-19T14:32:34.573297+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp1oioqcon']
[2024-06-19T14:32:36.787+0000] {standard_task_runner.py:63} INFO - Started process 514 to run task
[2024-06-19T14:32:36.788+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask test_task
[2024-06-19T14:32:36.830+0000] {task_command.py:426} INFO - Running <TaskInstance: testing_dag.test_task manual__2024-06-19T14:32:34.573297+00:00 [running]> on host 80ed35ae19d6
[2024-06-19T14:32:36.914+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_dag' AIRFLOW_CTX_TASK_ID='test_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T14:32:34.573297+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T14:32:34.573297+00:00'
[2024-06-19T14:32:36.916+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T14:32:36.917+0000] {logging_mixin.py:188} INFO - connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-06-19T14:32:36.917+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-19T14:32:36.918+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T14:32:36.927+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=testing_dag, task_id=test_task, run_id=manual__2024-06-19T14:32:34.573297+00:00, execution_date=20240619T143234, start_date=20240619T143236, end_date=20240619T143236
[2024-06-19T14:32:36.963+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-19T14:32:36.987+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-19T14:32:36.991+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
