[2024-06-19T13:23:06.864+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T13:23:06.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_dag.test_task manual__2024-06-19T13:23:04.573214+00:00 [queued]>
[2024-06-19T13:23:06.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_dag.test_task manual__2024-06-19T13:23:04.573214+00:00 [queued]>
[2024-06-19T13:23:06.900+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T13:23:06.917+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_task> on 2024-06-19 13:23:04.573214+00:00
[2024-06-19T13:23:06.925+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=582) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T13:23:06.928+0000] {standard_task_runner.py:63} INFO - Started process 586 to run task
[2024-06-19T13:23:06.928+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'test_task', 'manual__2024-06-19T13:23:04.573214+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp_pznct_1']
[2024-06-19T13:23:06.930+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask test_task
[2024-06-19T13:23:06.979+0000] {task_command.py:426} INFO - Running <TaskInstance: testing_dag.test_task manual__2024-06-19T13:23:04.573214+00:00 [running]> on host 06fa3b8001ae
[2024-06-19T13:23:07.599+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_dag' AIRFLOW_CTX_TASK_ID='test_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T13:23:04.573214+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T13:23:04.573214+00:00'
[2024-06-19T13:23:07.605+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T13:23:07.607+0000] {logging_mixin.py:188} INFO - connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-06-19T13:23:07.608+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-19T13:23:07.608+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T13:23:10.612+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=testing_dag, task_id=test_task, run_id=manual__2024-06-19T13:23:04.573214+00:00, execution_date=20240619T132304, start_date=20240619T132306, end_date=20240619T132310
[2024-06-19T13:23:10.712+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-19T13:23:10.838+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
