[2024-06-19T14:12:42.949+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T14:12:42.976+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_dag.task_3 manual__2024-06-19T14:12:40.194544+00:00 [queued]>
[2024-06-19T14:12:42.986+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_dag.task_3 manual__2024-06-19T14:12:40.194544+00:00 [queued]>
[2024-06-19T14:12:42.987+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T14:12:43.002+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_3> on 2024-06-19 14:12:40.194544+00:00
[2024-06-19T14:12:43.012+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T14:12:43.013+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'task_3', 'manual__2024-06-19T14:12:40.194544+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp_huwjefk']
[2024-06-19T14:12:43.013+0000] {standard_task_runner.py:63} INFO - Started process 188 to run task
[2024-06-19T14:12:43.014+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask task_3
[2024-06-19T14:12:43.063+0000] {task_command.py:426} INFO - Running <TaskInstance: testing_dag.task_3 manual__2024-06-19T14:12:40.194544+00:00 [running]> on host 80ed35ae19d6
[2024-06-19T14:12:43.178+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_dag' AIRFLOW_CTX_TASK_ID='task_3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T14:12:40.194544+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T14:12:40.194544+00:00'
[2024-06-19T14:12:43.180+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T14:12:43.182+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T14:12:43.183+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_dag.py", line 44, in init_load_ref_tables
    with conn:
TypeError: 'ConnectionAccessor' object does not support the context manager protocol
[2024-06-19T14:12:43.199+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_dag, task_id=task_3, run_id=manual__2024-06-19T14:12:40.194544+00:00, execution_date=20240619T141240, start_date=20240619T141242, end_date=20240619T141243
[2024-06-19T14:12:43.214+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task task_3 ('ConnectionAccessor' object does not support the context manager protocol; 188)
[2024-06-19T14:12:43.268+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T14:12:43.282+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T14:12:43.284+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
