[2024-06-20T15:22:51.766+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: testing_dag.copy_to_db manual__2024-06-20T15:22:20.629517+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
