[2024-06-19T13:00:11.995+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: testing_dag.test_task manual__2024-06-19T12:59:38.756717+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
