[2024-06-21T02:08:32.720+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T02:08:32.753+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gic_main_dag.transform scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-06-21T02:08:32.764+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gic_main_dag.transform scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-06-21T02:08:32.765+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-21T02:08:32.778+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-05-01 00:00:00+00:00
[2024-06-21T02:08:32.787+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=714) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T02:08:32.789+0000] {standard_task_runner.py:63} INFO - Started process 716 to run task
[2024-06-21T02:08:32.789+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gic_main_dag', 'transform', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpf1emqmv5']
[2024-06-21T02:08:32.791+0000] {standard_task_runner.py:91} INFO - Job 204: Subtask transform
[2024-06-21T02:08:32.837+0000] {task_command.py:426} INFO - Running <TaskInstance: gic_main_dag.transform scheduled__2024-05-01T00:00:00+00:00 [running]> on host 39e4faefdcb7
[2024-06-21T02:08:32.922+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gic_main_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-06-21T02:08:32.923+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T02:08:32.927+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T02:08:32.929+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_dag.py", line 72, in transform
    load_config_df = pd.read_csv(os.path.join(os.getcwd(), 'data/output/control_table_{}.csv'.format(load_time)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/output/control_table_1718935711975247000.csv'
[2024-06-21T02:08:32.950+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=gic_main_dag, task_id=transform, run_id=scheduled__2024-05-01T00:00:00+00:00, execution_date=20240501T000000, start_date=20240621T020832, end_date=20240621T020832
[2024-06-21T02:08:32.966+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 204 for task transform ([Errno 2] No such file or directory: '/opt/airflow/data/output/control_table_1718935711975247000.csv'; 716)
[2024-06-21T02:08:33.004+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-21T02:08:33.023+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-21T02:08:33.026+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
